### ISSUE TITLE
w_char vs char

### ISSUE THREAD

**Issue by whplh** [TrainingByPackt/BeginningCPlusPlus#7]
To find acces and comment to the errata takes way to much of my time. I spent 10 minutes without succes. Also the discussion better fits here.
In chapter one it is written:

Wide character: The wchar_t type is also used to represent character sets,
but allows for **greater size**. While char supports characters between 8 and 32 bits,
a wide character is 2 to 4 bytes long.

Which made me curious, because it's kind of like: 

On saturdays I weigh 80kg but on sundays I weigh 80000g. So on sundays I'm **bigger**.

But to point to the more interesting point for programming I found this article if you are curious:
https://stackoverflow.com/questions/45677774/char-vs-wchar-t-when-to-use-which-data-type/45679028

**Comment by MakersF** [comment]
Hi Philip,

thanks for the comment!

The C++ standard guarantees the **minimum** size for most of its types.
This is because if you need 2 bytes of space, you are guaranteed that a `wchar_t` will be able to hold them.
If `wchar_t` is bigger than 2 bytes, you can still store what you need into it, so the standard allows it.
This can be because on some CPUs it might be faster to use 4 bytes for `wchar_t`, and the standard does not want to forbid that.
Note that the size is fixed for a specific compilation: for a specific program any instance of the same type will have the same size.

Imagine you want to pack some books weighting 10kg.
You order online a box, and the website says "We guarantee the box can hold 10kg", so you buy it.
If you get a box that can hold 20kg it is not a problem, you can still put your books in it.

The problem would arise if they sent you a box which can hold less than 10kg.

If you need specific sizes for types, you can find the types defined here https://en.cppreference.com/w/cpp/types/integer

**Comment by whplh** [comment]
Hey thanks for the remark and the reference.
As I see it from cppreference and the discussion on stackoverflow. The actual use of wchar_t varies more with the operating system than with the architecture (8/16/32/64 bit) of the processor.
But I get it - char is at least UTF-8 and wchar_t is at least UTF-16 with the exception of windows where it is always UTF-16
